### ISSUE TITLE
Information about Structural Variant Allele Frequency estimation! 

### ISSUE THREAD

**Issue by poddarharsh15** [Han-Cao/collapse-bubble#1]
Hi @Han-Cao 
Thank you so much creating this tool, I have been struggling with merging and filtering VCF files with 441 samples. What would be the best practice to estimate Structural Variant Allele Frequency for outputs generated from the Dysgu tool on a cohort of 441 samples?[WES data aligned on GRCh38 ref.] Currently, I'm trying to use bcftools +fill-tags, but I’m not completely sure if it's accurately capturing the AF or [MAF/VAF]. 
If I use your pipeline to estimate these results, is it possible to estimate the AF of each variants to create panel on my cohort?  

Thanks for the help.

**Comment by Han-Cao** [comment]
Hi,

Thanks for your interest in this tool. 

Firstly, I would like to clarify that `collapse-bubble` is designed for pangenome VCFs that were generated using the [minigraph-cactus pipeline](https://github.com/ComparativeGenomicsToolkit/cactus), where all SVs were called from genome assemblies. Such a VCF is very different from the one you have (i.e., called from alignments). I believe this tool cannot be applied to your dataset.

Regarding your question, I would suggest you merge similar SVs first and then estimate AFs. SVs are usually merged based on SVTYPE, position, length, and sequence similarities. There are a lot of tools that you can try, like [truvari](https://github.com/ACEnglish/truvari), [jasmine](https://github.com/mkirsche/Jasmine), [SURVIVOR](https://github.com/fritzsedlazeck/SURVIVOR). I noticed Dysgu also has a function to merge SVs, but I don't have experience with it. Onece you merged similar SVs, you can estimate the AF by `bcftools +fill-tags -- -t AF`.

**Comment by poddarharsh15** [comment]
Thank you so much for your response! As you mentioned earlier, I’ve followed the suggested steps, but since I’m dealing with a large number of samples, merging causes a significant loss of GT information, making it tricky to estimate AF accurately. It seems like manually handling the data might be a better approach to minimize errors in AF calculation.

However, here’s the command I’ve been using for filtering and merging `my_cohort.vcf`:


```
bcftools merge -m none --force-samples --missing-to-ref -l "$MERGED_VCF_LIST" -Oz -o "$MERGED_VCF" --threads "$THREADS"
tabix "$MERGED_VCF"      

truvari collapse -i "$MERGED_VCF" \
                 -o "$TRUVARI_MERGED" \
                 -c "$TRUVARI_COLLAPSED" \
                 -f "$REF_GENOME" -k first -s 50 -S 10000000 --passonly -B 50 -r 2000 -p 0 -P 0.2 -O 0.2 --chain --typeignore

bcftools +fill-tags "${TRUVARI_COLLAPSED}.gz" \
         -Oz -o "$FINAL_OUTPUT" \
         --threads "$THREADS"

```
If you have any suggestions or improvements, I’d really appreciate your insights! Thanks again for your help.

**Comment by Han-Cao** [comment]
If you are using truvari collapse, I think it is better to ask the author of Truvari. 

I think the similarity cutoff you used it a bit low, but my experience was mainly on long-read sequencing not short-read sequencing data (as you mentioned WES, I suppose it is short-read sequencing). I am not sure what parameters should be used to merge SV called from short reads.
